name: Create a release on NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '1.0.0'
    
jobs:
  release-nuget:
  
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Pack
        run: dotnet pack Maui.Skeleton.sln -c Release
      - name: Push
        run: dotnet nuget push Maui.Skeleton\Maui.Skeleton\bin\Release\Plugin.Maui.Biometric.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
